name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      build-status: ${{ steps.set-status.outputs.status }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile and run tests
        run: ./gradlew clean build

      - name: Set build status
        id: set-status
        run: echo "::set-output name=status::success"
